### ISSUE TITLE
Lab 0

### ISSUE THREAD

**Issue by phuccodetrau** [neo4j-partners/hands-on-lab-neo4j-and-bedrock#12]
How can I find event code and information sheet  when signing up  OneBlink

**Comment by benofben** [comment]
The event code is given when you attend a lab in person.  If you're trying to work through the material online by yourself, you could use your own AWS account rather than one provisioned by OneBlink.ai.

At some point we'd like to offer these labs online but we're not quite there yet.  You can search for upcoming labs here: https://neo4j.com/events/?_event_search=hands%20on
